services:
  db-qualidade:
    image: postgres:15
    container_name: qualidade_db
    restart: always
    env_file:        
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME:-qualidade_db}       
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - qualidade_data:/var/lib/postgresql/data

  web-qualidade:
    build: .
    container_name: qualidade_web
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8000"
    command: >
      sh -c "python manage.py makemigrations --merge --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --worker-class gthread"
    environment:
      - DB_HOST=db-qualidade
      - DB_PORT=5432
    
    depends_on:
      - db-qualidade

volumes:
  qualidade_data: